# Generated by Django 4.2.3 on 2024-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='answers',
            field=models.ManyToManyField(to='submitter.answer'),
        ),
        migrations.AddField(
            model_name='listing',
            name='questions',
            field=models.ManyToManyField(to='submitter.question'),
        ),
    ]
