# Generated by Django 4.2.3 on 2024-02-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
