# Generated by Django 4.2.3 on 2024-01-21 21:01

from django.db import migrations, models
import submitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('submitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', submitter.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='listingresponse',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
