# Generated by Django 4.2.3 on 2024-03-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitter', '0002_listing_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Demographic', 'Demographic'), ('Social', 'Social'), ('Household', 'Household')], default='Demographic', max_length=200),
        ),
    ]
