# Generated by Django 4.2.3 on 2024-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitter', '0003_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='additional_information',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='available_bedrooms',
            field=models.IntegerField(choices=[(1, '1 Bedroom'), (2, '2 Bedrooms'), (3, '3 Bedrooms'), (4, '4 Bedrooms'), (5, '5+ Bedrooms')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_bedrooms',
            field=models.IntegerField(blank=True, choices=[(1, '1 Bedroom'), (2, '2 Bedrooms'), (3, '3 Bedrooms'), (4, '4 Bedrooms'), (5, '5+ Bedrooms')], null=True),
        ),
    ]
