# Generated by Django 4.2.3 on 2024-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitter', '0004_listing_additional_information_listing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='total_bedrooms',
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
